version: '3.9'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-04-13T03-08-07Z
    command: 'server --console-address ":9001" /data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - '9000'
      - '9001'
    volumes:
      - minio_data:/data

volumes:
    minio_data:
